// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5DC-udRdeXbyjiaxIFGuvRHRUxpq5Vjw',
    appId: '1:45584097556:web:16d3f2fdd58b1a8e0ce201',
    messagingSenderId: '45584097556',
    projectId: 'study-app-2-793ae',
    authDomain: 'study-app-2-793ae.firebaseapp.com',
    storageBucket: 'study-app-2-793ae.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAb6zHjMmSSEqfaEbBC-JAYAaoURkXc_XE',
    appId: '1:45584097556:android:67ef73cb924409ab0ce201',
    messagingSenderId: '45584097556',
    projectId: 'study-app-2-793ae',
    storageBucket: 'study-app-2-793ae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBESkUnDSIZ8s77PEvhKlNjQc__iAf3OhE',
    appId: '1:45584097556:ios:a5a8ccb3d439cb1c0ce201',
    messagingSenderId: '45584097556',
    projectId: 'study-app-2-793ae',
    storageBucket: 'study-app-2-793ae.appspot.com',
    iosBundleId: 'com.lohcy.studyApp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBESkUnDSIZ8s77PEvhKlNjQc__iAf3OhE',
    appId: '1:45584097556:ios:1cbfa29a540b24370ce201',
    messagingSenderId: '45584097556',
    projectId: 'study-app-2-793ae',
    storageBucket: 'study-app-2-793ae.appspot.com',
    iosBundleId: 'com.lohcy.studyApp2.RunnerTests',
  );
}
